### ISSUE TITLE
Conference joined without cat (conference access token)

### ISSUE THREAD

**Issue by malikusman-10p** [voxeet/voxeet-sdk-android#9]
**Bug Description**

Hi, According to the ConferenceJoinOptions in docs  it says that **_"The conference access token received from the create or invite REST API. The conference access token is required to join a protected conference."_** But in my experience most of the times SDK allows to join the conference without the access token which is I guess might be the security vulnerability (unless it doesn't work like I supposed).  

**Expected Behaviour**

It should always gives exception without the accessToken provided

**Steps to Reproduce the Problem**

1. Fetch the conference from conferenceId (VoxeetSDK.conference().fetchConference(confId))
2. Build the conferenceJoinOptions using the builder by passing the Conference object retrieved from the step 1st (it will return the options with null access token)
3. Try to join the conference with conferenceJoinOptions object (VoxeetSDK.conference().join(conferenceJoinOptions)) (it should throw the exception)
4. Repeat step 3 few times and conference will be joined

**Minimalistic code (recommended)**

`VoxeetSDK.conference().fetchConference(confId)
                .then(ThenPromise { conference: com.voxeet.sdk.models.Conference? ->
                    conference?.let {
                        val conferenceJoinOptions = ConferenceJoinOptions.Builder(
                            it
                        ).build()
                        VoxeetSDK.conference().join(conferenceJoinOptions)
                    }
                } as ThenPromise<com.voxeet.sdk.models.Conference?, com.voxeet.sdk.models.Conference>)
                .then<Any>(ThenVoid {
                    Log.d("Voxeet","Success: ${it.toString()}")
                })
                .error {
                    if (it is ServerErrorException) {
                        Log.e("ServerErrorException","Error: ${it.error}")
                    }
                }`

**Specifications**

  - Device: Samsung Galaxy A30
  - OS: Android 11
  - Platform: Android
  - Version: com.voxeet.sdk:sdk:3.3.0

**Comment by FabienLavocat** [comment]
@malikusman-10p Have you enabled the **Enhanced Conference Access Control** from your Dolby.io dashboard?

<img width="657" alt="Screen Shot 2022-03-03 at 11 26 41 AM" src="https://user-images.githubusercontent.com/4154532/156638288-e719bc5f-2a14-4cf7-a7dc-2bea2079595b.png">

Are you inviting the participant who's trying to join the conference using the invitation API?
Could you please provide an example of conference ID I will check the logs to understand what happened.

**Comment by malikusman-10p** [comment]
@FabienLavocat 
1. Yes we have enabled the enhanced conference access control in the dashboard
2. Yes we are using the invitation API to create accessToken for the participants
3. ConfId which I checked and was able to join even after the accessToken missing (**9f608d42-ac85-463d-8a98-b6750d90e4c2**)

**Comment by FabienLavocat** [comment]
Thank you @malikusman-10p for providing the information.

Looking at the logs, what I believe is happening is the following:
- Create the conference
- Invite the participant that is not yet connected (session not opened yet)
- The participant opens the application, open a session and tried to join the conference (failure 🔴)
- Your backend re-invite the participant, because the session is already open and a connection to our backend is opened, our backend will send a notification to the device. Your Android application can subscribe to the [InvitationReceivedNotificationEvent](https://docs.dolby.io/communications-apis/docs/android-client-sdk-notificationservice#invitationreceivednotificationevent) event. The notification from our backend contains the conference access token with the proper granular privileges. We will store this information temporarily in the SDK.
- The participant tried to join the conference without specifying an access token (success 🟢). In this case, joining the conference will work because the SDK has received the conference access token and stored it in memory.

Fabien

**Comment by malikusman-10p** [comment]
Thank you @FabienLavocat for looking into it the details and mentioning the steps what actually was happening. Going to close this issue.
